---
title: '2-8：异步代码的测试方法（2）'
date: 2019-07-25
permalink: 'test-learn-jest-async2'
---

lesson6 源码

继续上一小节的内容：

## resolves rejects

测试 promise 也可以这么写

```js
test('fetchData 返回结果为 { success: true }', () => {
  return expect(fetchData()).resolves.toMatchObject({
    data: {
      success: true
    }
  })
})
```

fetchData 请求成功后返回一个 promise 对象，再通过 `resolves` 进行求值，等同于 `fetchData().then()`

请求返回的 response 包含了很多 HTTP 的内容，比如请求头，config，data

之后通过 toMatchObject 去匹配，response 对象中是否有包含

```json
{
  "data": {
    "success": true
  }
}
```

以上是测试成功的情况，现在测试失败的情况，先修改 **fetchData** 请求的路径，随意改一个

```js
test('fetchData 返回结果为 404', () => {
  return expect(fetchData()).rejects.toThrow()
})
```

## async await

也可以使用 await，记得加上 async，有好几种方式可以测试，选用你觉得顺手的一种即可

```js
test('fetchData 返回结果为 { success: true }', async () => {
  // fetchData().then(res => console.log(res))
  await expect(fetchData()).resolves.toMatchObject({
    data: {
      success: true
    }
  })
})

test('fetchData 返回结果为 404', async () => {
  await expect(fetchData()).rejects.toThrow(
    'Request failed with status code 404'
  )
})

test('fetchData 返回结果为 { success: true }', async () => {
  const response = await fetchData()
  expect(response.data).toEqual({
    success: true
  })
})

test('fetchData 返回结果为 404', async () => {
  expect.assertions(1) // 强制执行 catch 里的 expect
  try {
    await fetchData()
  } catch (e) {
    console.log(e.toString()) // Error: Request failed with status code 404
    expect(e.toString()).toEqual('Error: Request failed with status code 404')
  }
})
```
