---
title: '2-7：异步代码的测试方法（1）'
date: 2019-07-25
permalink: 'test-learn-jest-async1'
---

lesson6 源码

测试一段发送请求的异步代码，首先安装 axios 发送请求

```sh
npm install axios@0.19.0 --save
```

将 --watchAll 改为 --watch

```json
{
  "scripts": {
    "test": "jest --watch",
    "coverage": "jest --coverage"
  }
}
```

```js
// fetchData.js
import axios from 'axios'
export const fetchData = fn => {
  axios.get('http://www.dell-lee.com/react/api/demo.json').then(res => {
    fn(res.data)
  })
}
```

```js
// fetchData.test.js
import { fetchData } from './fetchData'
test('fetchData 返回结果为 { success: true }', () => {
  fetchData(data => {
    expect(data).toEqual({
      success: true
    })
  })
})
```

如果直接这样测试，是可以通过的

![](https://raw.githubusercontent.com/ITxiaohao/blog-img/master/img/Jest/20190725222843.png)

但其实上面的测试代码写的是有问题的，因为 axios.get() 换成其他网页，返回的不是 { success: true } 也能通过测试

为什么？当运行测试用例的时候，**fetchData** 可以正常的执行，这个测试用例就**结束**了，不会等到里面的**回调函数结束**之后再测试

## done

在 test 的第二个回调函数里写一个 **done**，done 是一个**函数**，如果你**没有调用** done 函数就认为这个测试用例没有执行完成，只有调用了 done 才可以

```js {7}
import { fetchData } from './fetchData'
test('fetchData 返回结果为 { success: true }', done => {
  fetchData(data => {
    expect(data).toEqual({
      success: true
    })
    done()
  })
})
```

如果修改了请求地址，就会测试失败

![](https://raw.githubusercontent.com/ITxiaohao/blog-img/master/img/Jest/20190725223119.png)

## return Promise

修改 fetchData.js

```js
import axios from 'axios'
// export const fetchData = fn => {
//   axios.get('http://www.dell-lee.com/react/api/demo.json').then(res => {
//     fn(res.data)
//   })
// }

export const fetchData = () => {
  return axios.get('http://www.dell-lee.com/react/api/demo.json')
}
```

直接返回一个 Promise 对象

```js
test('fetchData 返回结果为 { success: true }', () => {
  // 将 Promise 返回
  return fetchData().then(res => {
    expect(res.data).toEqual({
      success: true
    })
  })
})
```

## expect.assertions()

```js
test('fetchData 返回结果为 404', () => {
  expect.assertions(1) // 至少执行一个 expect
  return fetchData().catch(e => {
    expect(e.toString().indexOf('404') > -1).toBe(true)
  })
})
```

如果不加 **expect.assertions(1)** ，1 是个数，接口没错的时候，是不会执行 catch 的，而是执行 then 方法

那么 catch 里面的代码就不会执行，所以也能通过测试，但这样是不对的，**必须**让 catch 里的 **expect** 执行

:::tip

当测试 promise 的时候，特别是测试 catch，**一定**要加 **expect.assertions()** 确保测试代码会执行

:::
